// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuv-Hjg6T8snoPC3lVzKt_MUuV3df-G78',
    appId: '1:620504000969:web:040505dd69156068fc6018',
    messagingSenderId: '620504000969',
    projectId: 'flutter-practice-chat',
    authDomain: 'flutter-practice-chat.firebaseapp.com',
    storageBucket: 'flutter-practice-chat.appspot.com',
    measurementId: 'G-YVXREYR2XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdY_CdPIUTDkjMD63taz47bOGM5sQtSFU',
    appId: '1:620504000969:android:f75cef9e432382f9fc6018',
    messagingSenderId: '620504000969',
    projectId: 'flutter-practice-chat',
    storageBucket: 'flutter-practice-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDomRRndO_5UT430FWmr4zjiNvSbQ4CkCk',
    appId: '1:620504000969:ios:5589559f7ee5a775fc6018',
    messagingSenderId: '620504000969',
    projectId: 'flutter-practice-chat',
    storageBucket: 'flutter-practice-chat.appspot.com',
    iosClientId: '620504000969-16hmducljao5jec4eo1e2b190avcoi7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDomRRndO_5UT430FWmr4zjiNvSbQ4CkCk',
    appId: '1:620504000969:ios:5589559f7ee5a775fc6018',
    messagingSenderId: '620504000969',
    projectId: 'flutter-practice-chat',
    storageBucket: 'flutter-practice-chat.appspot.com',
    iosClientId: '620504000969-16hmducljao5jec4eo1e2b190avcoi7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );
}
